---
# A list of global configuration variables
# Copy this file and rename to settings.yaml to override. You can also place the a settings.yaml
# file with the same format inside your project to more specific parameter needs.
settings:
    - project_path: '/home/dmb2/ODMProjects'
    - opensfm_pointcloud: True
    - opensfm_processes: 4  # Set this to nproc-2 for large datasets