on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: snapcore/action-build
      id: snapcraft
    - uses: actions/upload-artifact
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
